llm:
  provider: azure  # azure, openai, google
  model: gpt-4.1
  api_key: 
  endpoint: 
  api_version: "2024-02-15-preview"
  temperature: 0.7
  max_tokens: 4000

embedding:
  provider: azure  # azure, openai, google
  model: text-embedding-ada-002
  api_key: 
  endpoint: 
  api_version: "2024-02-15-preview"

tools:
  web_search:
    provider: zhipu  # zhipu big model search
    api_key: 
